"""Initial_db

Revision ID: 52050fef4396
Revises: e6ea23146469
Create Date: 2021-06-04 14:22:25.537190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52050fef4396'
down_revision = 'e6ea23146469'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anime', sa.Column('slug', sa.String(), nullable=True))
    op.drop_column('anime', 'length')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anime', sa.Column('length', sa.INTEGER(), nullable=True))
    op.drop_column('anime', 'slug')
    # ### end Alembic commands ###
